### ISSUE TITLE
Which version of lua to use?

### ISSUE THREAD

**Issue by shakfu** [pd3v/line#7]
I tried to build `line` on a raspberry pi 4 (with jack support) and could not pin down the version of lua that was required. 

Can you please provide some guidance on this?

**Comment by pd3v** [comment]
5.3.5

**Comment by shakfu** [comment]
Thanks!

**Comment by shakfu** [comment]
I've tried to install on macOS, Linux and in each case (with 5.3 installed as `liblua5.3-dev` in the case of linux), the cmake find logic just fails to find lua.h and  I have to overwrite your cmake file and set variables manually. Then after installing luarocks it can't even find lua.h and won't accept environment variables pointing it in the right direction,..

Maybe it's just me, but it's is becoming enough of a pain that I can imagine someone just dropping it and trying some [other livecoding tool](https://github.com/toplap/awesome-livecoding).

My suggestion is to specify a version of lua that is known to work and make it captive to your application. So basically cmake will download the source of this version, build it as a static lib and install to a local prefix (inside the cmake build directory), and then you compile your code and lpeg against it just using cmake (forget about luarocks). This means you have one buildsystem (cmake) which is designed to be multi-platform multi-architecture and you control all the variables to make it reproducible for users. I've done this before with luajit and it was way easier than getting different package managers to work as expected and in a consistent way.

**Comment by pd3v** [comment]
I've done this [build_all_but_readline_library](https://github.com/pd3v/line/tree/build_all_but_readline_library) branch where all line's dependencies are built and linked, except _readline_ library. If it is already on your system, an auto-search is performed by cmake and then linked, if not, please install _readline_ first. 
MacOS and Linux only. 
Have a try.

**Comment by shakfu** [comment]
@pd3v 

Worked for me ... Well done! 👍 

I had one minor issue thought: I was getting errors because `std::random_shuffle` was removed in c++17, and the advice is to use `random::shuffle`. 

I made the changes and it compiled without errors (file zipped and attached below)

[line.cpp.zip](https://github.com/pd3v/line/files/12130629/line.cpp.zip)
